export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT',
  INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT',
  REQUEST_POST = 'REQUEST_POST',
  RECEIVE_POSTS = 'RECEIVE_POSTS',
  FETCH_POSTS = 'FETCH_POSTS';
